---
- name: Install redshift
  pacman:
    name: redshift
    state: present

- name: Enable redshift user service
  systemd:
    name: redshift
    scope: user
    enabled: yes
  become: yes
  become_user: "{{ user.name }}"


- name: Create directory for service override
  file:
    path: "/home/{{ user.name }}/.config/systemd/user/redshift.service.d"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory

- name: Copy override to fix redshift startup issues
  copy:
    src: redshift-override.conf
    dest: "/home/{{ user.name }}/.config/systemd/user/redshift.service.d/override.conf"
  become: yes
  become_user: "{{ user.name }}"
