---
- hosts: localhost
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: editors }
    - { role: fonts, tags: ['fonts'] }
    - { role: microcode }
    - { role: xorg }
    - { role: i3, tags: ['i3'] }
    - { role: browsers, tags: ['browsers'] }
    - { role: redshift, tags: ['redshift'] }
  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password (only takes effect on creation)"
      unsafe: yes
      private: yes
