---
- hosts: localhost
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: user, tags: ['user'] }
    - { role: editors }
    - { role: fonts, tags: ['fonts'] }
    - { role: systemd-boot, tags: ['systemd-boot'] }
    - { role: xorg }
    - { role: sound }, tags: ['sound'] }
    - { role: desktop, tags: ['desktop'] }
    - { role: keyring, tags: ['keyring'] }
    - { role: browsers, tags: ['browsers'] }
    - { role: media, tags: ['media'] }
    - { role: redshift, tags: ['redshift'] }
  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password (only takes effect on creation)"
      unsafe: yes
      private: yes
