---
- hosts: localhost
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: microcode }
  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password (only takes effect on creation)"
      unsafe: yes
      private: yes
