---
- name: Install i3
  pacman:
    name: i3-gaps
    state: present

- name: Install i3lock
  pacman:
    name: i3lock
    state: present

- name: Install xss-lock
  pacman:
    name: xss-lock
    state: present

- name: Copy suspend@.service
  copy:
    src: suspend@.service
    dest: /etc/systemd/system/suspend@.service

- name: Enable suspend service
  systemd:
    name: "suspend@{{ user.name }}"
    enabled: yes

- name: Install additional desktop utilities
  pacman:
    name:
      - alacritty
      - dunst
      - gvfs-smb
      - pcmanfm
      - rofi
      - scrot
    state: present

- name: Install additional desktop utilities from AUR
  aur:
    name: polybar
    skip_installed: yes
  become: yes
  become_user: makepkg

- name: Install gnome theme and icons
  pacman:
    name:
      - materia-gtk-theme
      - papirus-icon-theme
