---
- name: Install feh
  pacman:
    name: feh
    state: present

- name: Install mpv
  pacman:
    name: mpv
    state: present

- name: Install youtube-dl
  pacman:
    name: youtube-dl
    state: present
