---
- name: Install sudo
  pacman: name=sudo state=present

- name: Enable wheel group
  lineinfile:
    path: /etc/sudoers.d/01-enable-wheel
    line: '%wheel ALL=(ALL) ALL'
    create: yes
    validate: 'visudo -cf %s'

- name: Create new user
  user:
    name: "{{ user.name }}"
    groups: "{{ user.groups }}"
    password: "{{ user_password|password_hash('sha512') }}"
    update_password: on_create
    append: yes

- name: Enable colour in pacman
  lineinfile:
    dest: /etc/pacman.conf
    regexp: '#Color'
    line: 'Color'

- name: Use multiple jobs to speed up compilation
  lineinfile:
    dest: /etc/makepkg.conf
    regexp: '^#MAKEFLAGS=\".+\"$'
    line: 'MAKEFLAGS="-j$(nproc)"'
