---
- name: Install fonts
  pacman:
    name: "{{ packages.fonts }}"
    state: present

- name: Enable subpixel rendering
  file:
    src: /etc/fonts/conf.avail/10-sub-pixel-rgb.conf
    dest: /etc/fonts/conf.d/10-sub-pixel-rgb.conf
    state: link

- name: Enable hinting
  file:
    src: /etc/fonts/conf.avail/10-hinting-slight.conf
    dest: /etc/fonts/conf.d/10-hinting-slight.conf
    state: link
